#Create Database Volumes
- name: Create Database Volume
  docker_volume:
    name: "{{ db_volume_name }}"
  register: created_db_volume

#Deploy the database based on the database type
- name: Deploy Database
  include_tasks: "{{ db_type }}_deploy.yml"