#Create the mysql configuration directory
- name: Creates mysql configuration directory
  file:
    path: '{{ mysql_configdir }}'
    state: directory

#Copy the IIQ configuration file to the mysql_config directory
- name: Copy IIQ Config File
  copy:
    src: '{{ mysql_config_file }}'
    dest: '{{ mysql_configdir }}/iiq-config-file.cnf'

#Deploy the database
- name: Deploy Database
  docker_container:
    name: "{{ db_container_name }}"
    image: "{{ db_image }}"
    published_ports:
      - "{{ db_port }}:3306"
    env:
      MYSQL_ROOT_PASSWORD: "{{ db_admin_password }}"
    volumes:
      - '{{ db_volume_name }}:/var/lib/mysql'
      - '{{ mysql_configdir }}:/etc/mysql/conf.d'
    networks:
      - name: "{{network_name}}"
    network_mode: "{{network_name}}"
    container_default_behavior: compatibility