#Deploy the database
- name: Deploy Database
  docker_container:
    name: "{{ db_container_name }}"
    image: "{{ db_image }}"
    published_ports:
      - "{{ db_port }}:{{ network_db_port }}"
    env:
      ORACLE_PASSWORD: "{{ db_admin_password }}"
    volumes:
      - '{{ db_volume_name }}:/opt/oracle/oradata'
    networks:
      - name: "{{network_name}}"
    network_mode: "{{network_name}}"
    container_default_behavior: compatibility